name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build-linux-executable
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: main.py
        spec: spec_file.spec

    - uses: actions/upload-artifact@v2
      with:
        name: Test
        path: dist
