name: Build PyQt5 App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Replace with your desired Python version

    - name: Install qmake and other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Package with PyInstaller
      run: |
        source venv/bin/activate
        pyinstaller spec_file.spec
        
    - name: Upload .exe as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: main # Replace with your desired artifact name
        path: ./dist/main.exe # Replace with the path to your generated .exe file
